# Generated by Django 6.0.1 on 2026-03-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_image_event_location_alter_event_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
